### ISSUE TITLE
Comentário em entrada/saida

### ISSUE THREAD

**Issue by douglascamata** [thiago-sydow/controle-de-ponto#100]
Poder adicionar comentários em entradas e saídas pode vir a ser muito útil para controle pessoal e também para informar melhor um possível "supervisor" (não sei se isso já existe).

**Comment by duduribeiro** [comment]
@douglascamata, um comentário para cada um dos registros? Pois você pode colocar comentários no dia inteiro, no campo "Observação". Isso resolve seu caso?
:smile: 
vlwwww

**Comment by douglascamata** [comment]
@duduribeiro acho que em cada um dos registros seria melhor. Por exemplo, um funcionário poderia explicar o motivo de uma saída inesperada, ou poderia colocar na entrada um comentário sobre qual tarefa estava fazendo...

**Comment by duduribeiro** [comment]
@thiago-sydow o que acha? É válido?

**Comment by thiago-sydow** [comment]
Vou manter aberto para ver se mais pessoas desejam. Isso atrapalharia bastante a usabilidade, ter uma observação por campo de horário. Se conseguir pensar em uma maneira que fique fácil sem poluir a interface, por favor sugira  :smile:

**Comment by thiago-sydow** [comment]
Como ninguém mais pediu por isso, e não é algo essencial vou fechar. Se alguém quiser desenvolver , fique a vontade. Na minha opnião uma observação geral é o caminho. Nela pode colocar o que quiser, inclusive "Entrada 1: estava fazendo etc.."
