### ISSUE TITLE
Problemas ao tentar ativar conta.

### ISSUE THREAD

**Issue by gabrielescodino** [thiago-sydow/controle-de-ponto#101]
Realizei o cadastro e o email de confirmação de conta demorou um pouco para chegar. Por isso, solicitei reenvio de email e recebi um suposto email para ativação da conta. 
O link do email me renderiza para a seguinte página: http://www.meucontroledeponto.com.br/users/confirmation/new
Esta página deveria ser a página de reenvio de email de confirmação e não de ativação da conta.
Dessa maneira, não é possível confirmar a conta e realizar o cadastro.

**Comment by thiago-sydow** [comment]
Oi Gabriel ! Não consegui ainda reproduzir o erro. Ativei sua conta para você poder usar enquanto investigo mais.

Abçs

**Comment by luizromariofilho** [comment]
Tive o mesmo problema que o Gabriel. Copiei o link que foi exibido no terminal com o token mas fica na página de reenvio de e-mail, e não na página de confirmação.

**Comment by thiago-sydow** [comment]
@luizromariofilho , o botão deve ser clicado, e não copiado. Não é um método GET que ativa a conta.
@gabrielescodino , você também copiou o link?

**Comment by luizromariofilho** [comment]
Ah sim, sou novo no ruby on rails, ainda não conheço muito. Vou tentar hoje.
