### ISSUE TITLE
Erro ao atualizar horário de almoço

### ISSUE THREAD

**Issue by cbfranca** [thiago-sydow/controle-de-ponto#103]
Ao tentar atualizar o tempo médio de almoço "estourou" um erro não tratado na tela.

**Comment by duduribeiro** [comment]
@cbfranca, o meu eu consegui atualizar normalmente =). vc pode informar quantos horários estavam preenchidos e os valores pra eu poder replicar aqui?

vlww 

abrass.

**Comment by thiago-sydow** [comment]
Relacionado ao #102

**Comment by duduribeiro** [comment]
:+1:

**Comment by cbfranca** [comment]
Somente uma entrada, sem nenhuma saída.
![capturar](https://cloud.githubusercontent.com/assets/1373328/7757941/63a5e8b4-ffdc-11e4-939e-6c6ee5a27e0b.JPG)

**Comment by duduribeiro** [comment]
@cbfranca legal.. como já está relacionado com outra issue, eu vou fechar e pode acompanhar pela #102 =)

**Comment by duduribeiro** [comment]
@cbfranca, é para estar certo agora.. Se puder testar =).
vlww

[]'s

**Comment by cbfranca** [comment]
Funcionou. Porém pediu a senha. Valeu!

Em sex, 22 de mai de 2015 às 15:29, Kadu Ribeiro <notifications@github.com>
escreveu:
