### ISSUE TITLE
Importar Registros de uma planilha

### ISSUE THREAD

**Issue by thiago-sydow** [thiago-sydow/controle-de-ponto#106]
Permitir importar registros contidos em uma planilha.

O formato deverá seguir o padrão :

Dia | Dia útil? | Faltou? | Horario | Horario | ............ | Observações

**Comment by thiagodorneles** [comment]
Não sei se a coluna de dia útil é necessária.
Verificando se é um dia da semana e que não seja feriado pode ser considerado dia útil.
E finais de semana talvez através seja possível identificar quais dias da semana o usuário trabalha, até mesmo para contabilizar os horários.

**Comment by thiago-sydow** [comment]
Permitir o usuário configurar quais dias são úteis realmente realmente é uma opção. Já a parte de feriado, não me agrada muito ter que ficar cadastrando feriados. Feriados variam de cidade/usuário. Se souber de algum lugar de onde pegar isso de forma mais automática, sem o usuário ter que cadastrar tudo,  seria bom :smile:

**Comment by thiagodorneles** [comment]
Tem alguns lugares que pode consultar os feriados. Só não sei se abrangem a cidade.

Peguei alguns links rapidamente aqui:
- [http://eferiado.com/api/](http://eferiado.com/api/)
- [API do Google calendar] (https://developers.google.com/google-apps/calendar/v3/reference/)

[Aqui](http://www.guj.com.br/19914-identificacao-de-feriados-nacionais-via-api) tem um exemplo bem simples usando google calendar que achei do pessoal fazendo em Java mesmo. Mas da para ter uma ideia.
