### ISSUE TITLE
Tempo de carência

### ISSUE THREAD

**Issue by thiagodorneles** [thiago-sydow/controle-de-ponto#113]
Adicionar uma configuração para determinar um tempo de carência para então contabilizar horários.

Na empresa onde trabalho temos uma carência diária de 15 minutos, ou seja, se eu ficar devendo até 15 minutos em um dia isso não é descontado, porém o oposto também é verdade, se eu fizer até 15 minutos de horas extras isso também não é pago.

*Obs: Não sei se isso é lei ou apenas uma característica da empresa onde trabalho*

**Comment by thiago-sydow** [comment]
Entendi Thiago. Qual seria o comportamento esperado nesse caso? O saldo deve 'abater" sozinho 15 minutos ou algum outro?

**Comment by thiagodorneles** [comment]
No meu caso o tempo seria abatido.

Talvez até poderia exibir que fiquei devendo 10 minutos naquele dia, porém isso não pode contabilizar no meu saldo de horas.
