### ISSUE TITLE
Opção para atestados médicos

### ISSUE THREAD

**Issue by adelmo00** [thiago-sydow/controle-de-ponto#123]
Poderia ser criada uma opção de colocar atestados médicos para não ficar com saldo devedor ou ter que colocar o total de horas trabalhadas, sendo que não foram trabalhadas.

**Comment by thiago-sydow** [comment]
Se você cadastrar um registro como "Dia útil" = não, e remover todos os horários.
Ele vai marcar como 00:00 não afetando o saldo. Isso não atende?

**Comment by adelmo00** [comment]
Mas é o dia é útil e algumas horas foram trabalhadas. Exemplo: Ontem mesmo tive que sair para ir ao médico, e não voltei mais, mas se tivesse dado tempo eu voltaria. Nesse caso de ontem tive que colocar todas as horas, como se não tivesse saído para ir ao médico, para não ficar com o saldo negativo.

**Comment by thiago-sydow** [comment]
Ah sim, realmente. vou adicionar no backlog :+1:
