### ISSUE TITLE
Possibilitar que o usuário atualize mais dias de trabalho

### ISSUE THREAD

**Issue by mauricioleoncio** [thiago-sydow/controle-de-ponto#155]
Como é hoje:
Hoje se um usuário esquecer de registrar o ponto por N dias, ele deverá adicionar um registro por vez.

Como deve ser:
Durante a edição o usuário poderá atualizar um ou mais dias de trabalho.

**Comment by mdsrosa** [comment]
Acho que essa seria uma ótima feature. Hoje mesmo precisei adicionar os horários de 1 semana atrás. Tive que adicionar um a um.

Outro modo de fazer isso, seria a possibilidade de "duplicar" os horários existentes adicionando essa opção na coluna "Ações" na tela com a listagem dos horários.

**Comment by thiago-sydow** [comment]
Duplicar acabaria levando para a tela de edição para alterar para o horário que deseja.

A solução que eu tinha pensado era no form ter mais um botão "Salvar e adicionar outro". Clicando nele iria adicionar/atualizar o registro e permanecer na tela para adicionar outro.

Resolve os problemas @mdsrosa @mauricioleoncio ?

**Comment by mdsrosa** [comment]
@thiago-sydow Boa! Pra mim já resolve! :+1:

**Comment by mauricioleoncio** [comment]
@thiago-sydow Opa! Vai ficar top! :dancer:

**Comment by thiago-sydow** [comment]
Closed via #160
