### ISSUE TITLE
Popover para adicionar o horário não fecha ao mudar o foco de um campo para outro

### ISSUE THREAD

**Issue by mdsrosa** [thiago-sydow/controle-de-ponto#156]
![screen shot 2015-09-08 at 4 29 24 pm](https://cloud.githubusercontent.com/assets/1862239/9745473/79bf30ca-5648-11e5-9803-989694e22abd.png)

Para reproduzir o bug:
1. Entrar no formulário "Novo Registro".
2. Clicar 3x no botão "+" para adicionar os campos de entrada e saída.
3. Clicar no primeiro campo de entrada.
4. Apertar 6x a tecla `tab`.

**Comment by thiago-sydow** [comment]
Closed via #159
