### ISSUE TITLE
Sistema não está validando valor vazio para os horários

### ISSUE THREAD

**Issue by mdsrosa** [thiago-sydow/controle-de-ponto#157]
Antes de enviar o formulário
![screen shot 2015-09-08 at 4 48 59 pm](https://cloud.githubusercontent.com/assets/1862239/9745656/9e6e835c-5649-11e5-8e2b-5087a050b951.png)

Depois de enviar o formulário
![screen shot 2015-09-08 at 4 49 15 pm](https://cloud.githubusercontent.com/assets/1862239/9745664/a8e48b6a-5649-11e5-96cd-1f006fac7170.png)

**Comment by duduribeiro** [comment]
Acho q podemos colocar uma validação de ao menos um registro.
o que acha @thiago-sydow ?

vc vai tentar desenvolver @mdsrosa ?

abrass

**Comment by mdsrosa** [comment]
@duduribeiro Acabei de fazer o fork do projeto, vou tentar fazer por aqui. Se der certo, envio o PR assim que der.

**Comment by duduribeiro** [comment]
:+1: 

qualquer coisa, pinga a gente ae.. 

:beers:

**Comment by thiago-sydow** [comment]
Massa, só considere o cenário. A pessoa vai marcar que Faltou, ela será obrigada a ter um registro de entrada mesmo assim (mesmo que não faça nada nas contas). 

Permito em branco justamente para esse tipo de caso. 

Se for validar, sugiro não validar/fazer algo para quando a pessoa selecionar que faltou

**Comment by mdsrosa** [comment]
@thiago-sydow Entendido!
