### ISSUE TITLE
Plantões

### ISSUE THREAD

**Issue by charlesduarte019** [thiago-sydow/controle-de-ponto#241]
Não sei se tem, mas como faço para dar a entrada no dia X e a saída no dia X+1.
E as horas serem contabilizada como positivamente?
Tentei fazer isso, ou a entrada do ponto, e não coloco a saída. No outro dia quando é para colocar o ponto, ele já informa que é a entrada.

Ps.: Procurei já outros sistemas, mas nenhum contém esta funcionalidade.

**Comment by thiago-sydow** [comment]
Não é possível mesmo. Todo o cálculo ocorre em um mesmo dia, não entre dias
