### ISSUE TITLE
Cálculo hora x valor modalidade pj não confere

### ISSUE THREAD

**Issue by paulamilani** [thiago-sydow/controle-de-ponto#245]
Configurando meu controle de ponto em modalidade PJ e preenchendo valor hora, após lançar as entradas e saídas, o resultado do calculo no campo "Ganhos" não condiz com as informações. Passou a ocorrer após realizar um fechamento.
Acredito que esteja contabilizando o ultimo dia do ultimo fechamento, tanto para o "Saldo de horas" como para os "Ganhos".

**Comment by EzequielMessore** [comment]
+1

**Comment by thiago-sydow** [comment]
Sim, ganhos e saldo de horas na lateral sao sempre considerados à partir de fechamentos
