### ISSUE TITLE
Saldo de horas não bate com o saldo total

### ISSUE THREAD

**Issue by EzequielMessore** [thiago-sydow/controle-de-ponto#255]
Fiz um fechamento do dia 01/01/2020 a 31/01/2020, e conforme fui lançando mais horas o saldo de horas começou a ficar diferente da realidade, quando faco um filtro pelo mes me mostra correto.

![image](https://user-images.githubusercontent.com/11234992/74731977-fd97af00-5227-11ea-8a93-315b8455a8be.png)

**Comment by thiago-sydow** [comment]
O saldo mostrado no menu lateral é calculado no período entre o último fechamento registrado (ou desde o primeiro horário da conta se não tiver fechamento) e o dia atual. Ele não aplica o filtro de data usado na tabela. Por isso os dois são divergentes

**Comment by thiago-sydow** [comment]
O saldo mostrado no menu lateral é calculado no período entre o último fechamento registrado (ou desde o primeiro horário da conta se não tiver fechamento) e o dia atual. Ele não aplica o filtro de data usado na tabela. Por isso os dois são divergentes
