### ISSUE TITLE
Redirecionar para home ao clicar na logo

### ISSUE THREAD

**Issue by rennancockles** [thiago-sydow/controle-de-ponto#259]
![image](https://user-images.githubusercontent.com/2038003/75607629-ef734980-5ad7-11ea-91b5-7bdf1bb62b84.png)

Ao clicar na logo no lado superior esquerdo o usuário deveria ser redirecionado para a home "http://www.meucontroledeponto.com.br/", porém está apenas incluindo um hash (#) no final no link atual.
Exemplo: http://www.meucontroledeponto.com.br/closures/new#

**Comment by thiago-sydow** [comment]
Atualizado, obrigado!
