### ISSUE TITLE
Docker para desenvolvimento

### ISSUE THREAD

**Issue by gabsprates** [thiago-sydow/controle-de-ponto#269]
Olá!

Pelo que vi, as dependências de plataforma do projeto são Ruby e PostgreSQL, certo?

Já pensaram em criar um `Dockerfile`, ou `docker-compose.yml`, encapsulando essas dependências, pra facilitar (pelo menos) o desenvolvimento?

Pergunto porque, como desenvolvedor frontend que tem certa experiência com backend mas zero experiência com Ruby, ou Rails, gostei da ideia do projeto e gostaria de poder contribuir com código de alguma forma, mas sem precisar inchar (ou instalar coisas que não uso no meu dia-a-dia) meu ambiente local. Acredito que isso pode ser bom pra qualquer pessoa.

O que acham?

**Comment by rafaelvschneider** [comment]
Acho bem interessante ser criado por esses mesmos motivos que citou na abertura desta issue, também gostaria de contribuir no projeto sem necessitar instalar dependências que não costumo utilizar no dia-a-dia.
