### ISSUE TITLE
Não permitir registrar ponto futuro ou editar ponto passado

### ISSUE THREAD

**Issue by valessiobrito** [thiago-sydow/controle-de-ponto#84]
Atualmente o sistema permite edição do ponto de dias anteriores ou registrar pontos futuros.  Sugiro travar a tela de registro e suporte edição de ponto ao dia atual.

Parabéns pelo trabalho!

**Comment by thiago-sydow** [comment]
Olá Valessio !

Primeiramente obrigado por usar e ajudar a melhorar o sistema.

Concordo com travar pontos futuros, mas não permitir editar dias anteriores não faz muito sentido na minha opinião. 
Se a pessoa esquecer de registrar o horário na hora que sair do trabalho, não poderá inserí-lo no dia seguinte? Existe algum motivo ou cenário para a pessoa não poder mesmo fazer isso?

**Comment by valessiobrito** [comment]
Thiago, você pode fazer essa função parametrizavel no sistema?  Tipo, no arquivo de configuração.   Já foi dada a flexibilidade para ele editar/marcar durante o Dia;  Se ele não marcou, a única coisa que poderia fazer é escrever uma justificativa porque faltou/não marcou.

**Comment by thiago-sydow** [comment]
Valessio, foi impedido de salvar uma data futura. Quanto à não permitir editar uma data passada, estou montando um milestone que envolve a possibilidade de fazer isso, bem como o painel de supervisão, já que estaria mais focado à quem supervisiona impossibilitar ou não um usuário de realizar isto.

Faz sentido ?

**Comment by valessiobrito** [comment]
Sim, isso já será muito útil.  Obrigado pelo seu trabalho!

**Comment by thiago-sydow** [comment]
Estou centralizando qualquer coisa referente ao "toque corporativo"  no #86.
