### ISSUE TITLE
Apresentar a justificativa no relatório

### ISSUE THREAD

**Issue by valessiobrito** [thiago-sydow/controle-de-ponto#85]
Atualmente quando não se registra hora de entrada e saída, quando marca "Falta" e escreve uma "Anotação" o mesmo não é exibido no relatório (listagem detalhada do ponto);

Sugiro apresentar a anotação nos campos em branco, quando justificada a falta.

**Comment by thiago-sydow** [comment]
Olá !

A issue #87 irá tratar isso. Será exibida a observação/justificativa quando em um tooltip ou algo do gênero quando o mouse ficar em cima da linha. Assim, será exibido sempre, independentemente de haver ou não regitros de horas.

Isso atenderá?

**Comment by valessiobrito** [comment]
Então, o problema do Tooltip é que não vai sair na Impressão;  Do jeito que esta hoje um "Ctrl+P' gera um relatório desejavel, faltando apenas indicar a justificativa na ausência de marcação.  

Estou pensando na visibilidade dessa informação em modo de impressão / relatório;

**Comment by thiago-sydow** [comment]
Entendi, estou fazendo uma issue que irá implementar a funcionalidade de exportar os registros para PDF, e talvez mais pra frente CSV/XLS.

Irei incluir a observação no pdf gerado de alguma forma, serve?

**Comment by thiago-sydow** [comment]
Estou fechando a issue, a observação pode ser vista do PDF exportado.

Se não atender seu caso, reabra por favor ;)
