### ISSUE TITLE
Refactor Javascripts

### ISSUE THREAD

**Issue by thiago-sydow** [thiago-sydow/controle-de-ponto#94]
Fazer refactor dos javacripts, separar por controllers

**Comment by urieljuliatti** [comment]
Já pensou em refatorar para CoffeeScript, contemplando OO e um código mais limpo e legível (ruby-way)?

**Comment by duduribeiro** [comment]
Não é necessário CoffeeScript para fazer um bom código JS :smile: .
Pode ser feito utilizando Javascript mesmo.

[]'s

**Comment by urieljuliatti** [comment]
@duduribeiro Eu sei. Foi só uma sugestão =)

**Comment by duduribeiro** [comment]
É q eu ainda prefiro JS msm, sem Coffee kkkk.

vlw
[]'s

**Comment by urieljuliatti** [comment]
@duduribeiro hahaha eu o compreendo! A idéia é refatorar, principalmente, o que está aqui: https://github.com/thiago-sydow/controle-de-ponto/blob/master/app/assets/javascripts/backend-common.js e aqui: https://github.com/thiago-sydow/controle-de-ponto/blob/master/app/assets/javascripts/ajax_update.js ?

Abraço!

**Comment by thiago-sydow** [comment]
Na verdade tá com muito javascript desnecessário por causa do tema. Como vou ter que trocar ele, pois a licença descobri que não permite deixar "público" para outros usarem, é caracterizado como redistribuição, já pretendo enxugar tudo.
